# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e673be471e67c89bd48974d7b2ae5b91d4864711e1a36f3192bbdf7e06912c6c86a3f10697eb2fc21a4323481261ee9bdb16d18f6739e0bd7100165479c6cd73

test:
  secret_key_base: 80e2dcf56bbbbb05a7e51003f052b46645832e4dad61e09ceb093b50a4c54de7d542c99b13b8ce92f81ed45696bc3347fd8d854ae1d155f424856f7dd5ba8279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
